/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apisylux.smsbackup;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author ahsan
 */
public class MySqlConfigFrame extends javax.swing.JFrame {
    
    String MySqlURL = "";
    String UserName = "";
    String Password = "";
    
    
    
    public MySqlConfigFrame() {
        initComponents();
        this.setVisible(rootPaneCheckingEnabled);
        this.setSize(500,300);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MySqlURLLAble = new javax.swing.JLabel();
        MySqlUrlText = new javax.swing.JTextField();
        MySqlUsernameText = new javax.swing.JTextField();
        MySqlUserName = new javax.swing.JLabel();
        MySqlPasswordText = new javax.swing.JTextField();
        MySqlPasswordLabel = new javax.swing.JLabel();
        MySqlUpdateButton = new javax.swing.JButton();
        MySqlCancelButton = new javax.swing.JButton();
        PortLabel = new javax.swing.JLabel();
        MySqlPortText = new javax.swing.JTextField();
        DatabaseNameLabel = new javax.swing.JLabel();
        MySqlDatabaseText = new javax.swing.JTextField();
        WarningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MySqlURLLAble.setText("URL (Default: LocalHost)");

        MySqlUrlText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MySqlUrlTextActionPerformed(evt);
            }
        });

        MySqlUsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MySqlUsernameTextActionPerformed(evt);
            }
        });

        MySqlUserName.setText("Username");

        MySqlPasswordLabel.setText("Password");

        MySqlUpdateButton.setText("Update");
        MySqlUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MySqlUpdateButtonActionPerformed(evt);
            }
        });

        MySqlCancelButton.setText("Cancel");
        MySqlCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MySqlCancelButtonActionPerformed(evt);
            }
        });

        PortLabel.setText("Port (Default: 3306)");

        DatabaseNameLabel.setText("Database Name");

        WarningLabel.setText("");
        WarningLabel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WarningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MySqlUrlText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MySqlURLLAble, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MySqlUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MySqlUsernameText)
                            .addComponent(MySqlPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MySqlPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(MySqlPortText)
                            .addComponent(MySqlDatabaseText)
                            .addComponent(DatabaseNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MySqlUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MySqlCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MySqlURLLAble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MySqlUrlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MySqlUserName)
                    .addComponent(PortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MySqlUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MySqlPortText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MySqlPasswordLabel)
                    .addComponent(DatabaseNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MySqlPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MySqlDatabaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(WarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MySqlCancelButton)
                    .addComponent(MySqlUpdateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MySqlUsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MySqlUsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MySqlUsernameTextActionPerformed

    private void MySqlUrlTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MySqlUrlTextActionPerformed
        
    }//GEN-LAST:event_MySqlUrlTextActionPerformed

    private void MySqlCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MySqlCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_MySqlCancelButtonActionPerformed

    private void MySqlUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MySqlUpdateButtonActionPerformed
        String CompleteUrl = "";
        String PortNumber = "";
        String DatabaseName = "";
        DatabaseName = MySqlDatabaseText.getText();
        if(DatabaseName.equals("")){
            WarningLabel.setText("Database Name is Missing! Please close and open window Again.");
        }
        
        MySqlURL = MySqlUrlText.getText();
        PortNumber = MySqlPortText.getText();
        if(PortNumber.equals("")){
            PortNumber = "3306";
        }
        
        if(MySqlURL.equals("")){
            MySqlURL = "localhost";
        }
        CompleteUrl = "jdbc:mysql://"+MySqlURL+":"+PortNumber+"/";
        
        UserName = MySqlUsernameText.getText();
        if(UserName.equals("")){
            WarningLabel.setText("Username is Missing! Please close and open window Again.");
        }
        
        
        Password = MySqlPasswordText.getText();
        if(Password.equals("")){
            WarningLabel.setText("Password is Missing! Please close and open window Again.");
        }
        
        File file = new File("dbconnect.txt");
        WarningLabel.setVisible(true);
        try {
            if(WarningLabel.getText().equals("")){
                file.createNewFile();
                FileWriter writer = new FileWriter(file);
                writer.append(CompleteUrl);
                writer.append("\n");
                writer.append(DatabaseName);
                writer.append("\n");
                writer.append(UserName);
                writer.append("\n");
                writer.append(Password);
                writer.flush();
                writer.close();
                
                this.dispose();

            }
        
            
//            FileReader reader = new FileReader(file);
//            BufferedReader br = new BufferedReader(reader);
//            
//            while(br.ready()){
//                System.out.println(br.readLine());
//            }
//            
            
//        MainFrame main = new MainFrame();
        } catch (IOException ex) {
            Logger.getLogger(smsbackup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_MySqlUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MySqlConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MySqlConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MySqlConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySqlConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MySqlConfigFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatabaseNameLabel;
    private javax.swing.JButton MySqlCancelButton;
    private javax.swing.JTextField MySqlDatabaseText;
    private javax.swing.JLabel MySqlPasswordLabel;
    private javax.swing.JTextField MySqlPasswordText;
    private javax.swing.JTextField MySqlPortText;
    private javax.swing.JLabel MySqlURLLAble;
    private javax.swing.JButton MySqlUpdateButton;
    private javax.swing.JTextField MySqlUrlText;
    private javax.swing.JLabel MySqlUserName;
    private javax.swing.JTextField MySqlUsernameText;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JLabel WarningLabel;
    // End of variables declaration//GEN-END:variables
}
